config/routes.rb
SampleApp::Application.routes.draw do
  devise_for :users,:controllers => {:registrations => "registrations"}
  resources :home, :only => :index
  resources :users
  
  get "pages/contact"
  get "pages/about"
  get "pages/help"

  get "results/result"
  get "results/wiki_results"
  get "results/job_results"
  get "results/image_results"
  get "results/news_results"
  
  post "deleteFolder" => 'tree#deleteFolder'
  post "insertResult" => 'tree#insertResult'
  post "createFolder" => 'tree#createFolder'
  post "deleteResult" => 'tree#deleteResult'
  
  get "mapLoc" => 'map#getLocationMap'
  get "weather"=> 'map#getWeatherMap'
  get "address" => 'map#getAddressMap'

  match '/contact' , :to => 'pages#contact'
  match '/about' , :to => 'pages#about'
  match '/help' , :to => 'pages#help'
  match '/bubble', :to => 'home#bubbleAnswer'
  
  match '/web' , :to => 'results#result'
  match '/wiki' , :to => 'results#wiki_results'
  match '/job' , :to => 'results#job_results'
  match '/news' , :to => 'results#news_results'
  match '/img' , :to => 'results#image_results'
  
  match '/webh' , :to=> 'home#index'
  match '/wikih', :to=> 'home#wiki_index'
  match '/imgh', :to=> 'home#img_index'
  match '/newsh', :to=> 'home#news_index'
  match '/jobh', :to=> 'home#job_index'
  root :to => 'home#index'

  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
    
  end
 

end

app/views/layouts/resultPage/_results_header.html.erb
<header>
	<% logo= image_tag("logo_black.jpg",:alt => "Bunchit App",:id=>"logo",:class => "round",:height => "25",:width => "155") %>
	<%= link_to logo, root_path,:class=>"span-5"%>
	<%=form_tag "/"+@source_setting,:method=>"get",:id=>"queryFormResultsPage",:onSubmit=>"return validate();",:id=>"searchForm" do%>
	<%= text_field_tag :query, @query,:size=>50,:id=>"searchBarResults",:class=>"searchBar span-10",:autocomplete=>"off"%>
	<%= submit_tag "",:name=>nil,:id=>"searchButtonResultsPage",:onSubmit=>"alert('sadfasf')" %>
	
	<script>
		! function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if(!d.getElementById(id)) {
				js = d.createElement(s);
				js.id = id;
				js.src = "//platform.twitter.com/widgets.js";
				fjs.parentNode.insertBefore(js, fjs);
			}
		}(document, "script", "twitter-wjs");
	</script>
	<!-- Disable browser cache-->
	<script>
		function OperaReload() {
			try {
				var headElement = document.getElementsByTagName("head")[0];
				if(headElement && headElement.innerHTML)
					headElement.innerHTML += "<meta http-equiv=\"refresh\" content=\"1\">";
			} catch (e) {
			}
		}
	</script>

	<script>
		! function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if(!d.getElementById(id)) {
				js = d.createElement(s);
				js.id = id;
				js.src = "//platform.twitter.com/widgets.js";
				fjs.parentNode.insertBefore(js, fjs);
			}
		}(document, "script", "twitter-wjs");

	</script>
	<nav class="round">
		<ul>
			<li>
				<%= link_to "Home", root_path%>
			</li>
			<li>
				<%= link_to "What is Bunch<it>", help_path %>
			</li>
			<% if signed_in? %>
			<li>
				<%= link_to 'Sign out', logout_path, :method => :delete %>
			</li>
			<li>
				<%= link_to "Profile "+current_user.user_name, user_path(@user), :method => :delete %>
			</li>
			<% else %>
			<li>
				<%= link_to "Sign in", new_user_session_path %>
			</li>
			<% end %>
		</ul>
	</nav>
	<%end%>
	<!--<a href="https://twitter.com/BunchItSearch" class="twitter-follow-button" data-show-count="false">Follow Us</a>-->
</header>

app/views/layouts/resultPage/_video_overlay.html.erb
<div class="videoDialog">
	<div id="videoDialog" title="Youtube Video">
		<iframe title="YouTube video player" class="youtubePlayer" type="text/html" width="560"
		height="315" src="http://www.youtube.com/embed/{ID}" frameborder="0"
		allowFullScreen></iframe>
	</div>
</div>

app/views/layouts/resultPage/_visual_selector.html.erb
<span id="changeVisualButtonSet" style="display:none;">
	<input type="button" id="changeVisualButton" value="Tag Cloud"  onclick="changeVisual();"/>
</span>